version: '3.8'

services:
  ros:
    container_name: ros-noetic
    # ttyを入れないとすぐに終了する
    tty: true
    build:
      dockerfile: Dockerfile
      context: .
    network_mode: "host"
    volumes:
      - type: bind
        source: .
        target: /root/catkin_ws/src/catchrobo
    environment:
      ROS_MASTER_URI: http://172.17.0.1:11311
      ROS_IP: 172.17.0.1
      ROS_HOSTNAME: 172.17.0.1
